/* Generated by TOM (version 20080516 (src)): Do not edit this file */package test;

public class Example {
  public String toString() {
    return "Example";
  }
  static class JavaType { 
    JavaType(Example e) {
      child = e;
    }
    Example child;
    Example getChild() { return child; };
    public String toString() {
      return "JavaType(" + getChild() + ")";
    }
  }


  public static void main(String[] args) {
    System.out.println("Hello");
    Example t = new Example();
    JavaType b = tom_make_A(t);
    Example c = tom_make_C();
    {{ Object tomMatch1NameNumber_freshVar_0=b;if (tom_is_sort_TomType(tomMatch1NameNumber_freshVar_0)) {{  JavaType  tomMatch1NameNumberfreshSubject_1=(( JavaType )tomMatch1NameNumber_freshVar_0);{  JavaType  tom_c=tomMatch1NameNumberfreshSubject_1;if ( true ) {

        System.out.println(c); 
        System.out.println(tom_c); 
      }}}}}}

  }

  private static boolean tom_is_sort_TomType(Object t) {return  t instanceof JavaType ;}private static boolean tom_is_sort_TomType2(Object t) {return  t instanceof Example ;}private static  JavaType  tom_make_A( Example  x) { return  new JavaType(x) ;}private static  Example  tom_make_C() { return  new Example() ;}


















}
