//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 08:11:09 AM GMT 
//


package rtxf;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}typeref"/>
 *       &lt;/choice>
 *       &lt;attribute name="classname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fieldname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="fields" type="{http://www.w3.org/2001/XMLSchema}NMTOKENS" />
 *       &lt;attribute name="encapsulate" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="toplevel" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "typeref"
})
@XmlRootElement(name = "extract_class")
public class ExtractClass {

    protected Typeref typeref;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String classname;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String fieldname;
    @XmlAttribute
    @XmlSchemaType(name = "NMTOKENS")
    protected List<String> fields;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String encapsulate;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String toplevel;

    /**
     * Gets the value of the typeref property.
     * 
     * @return
     *     possible object is
     *     {@link Typeref }
     *     
     */
    public Typeref getTyperef() {
        return typeref;
    }

    /**
     * Sets the value of the typeref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Typeref }
     *     
     */
    public void setTyperef(Typeref value) {
        this.typeref = value;
    }

    /**
     * Gets the value of the classname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassname() {
        return classname;
    }

    /**
     * Sets the value of the classname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassname(String value) {
        this.classname = value;
    }

    /**
     * Gets the value of the fieldname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFieldname() {
        return fieldname;
    }

    /**
     * Sets the value of the fieldname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFieldname(String value) {
        this.fieldname = value;
    }

    /**
     * Gets the value of the fields property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fields property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFields().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getFields() {
        if (fields == null) {
            fields = new ArrayList<String>();
        }
        return this.fields;
    }

    /**
     * Gets the value of the encapsulate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEncapsulate() {
        return encapsulate;
    }

    /**
     * Sets the value of the encapsulate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEncapsulate(String value) {
        this.encapsulate = value;
    }

    /**
     * Gets the value of the toplevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToplevel() {
        return toplevel;
    }

    /**
     * Sets the value of the toplevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToplevel(String value) {
        this.toplevel = value;
    }

}
