//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.16 at 08:11:09 AM GMT 
//


package rtxf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{}pkgref"/>
 *         &lt;element ref="{}typeref"/>
 *         &lt;element ref="{}methodref"/>
 *         &lt;element ref="{}fieldref"/>
 *         &lt;element ref="{}tempref"/>
 *       &lt;/choice>
 *       &lt;attribute name="newname" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "pkgref",
    "typeref",
    "methodref",
    "fieldref",
    "tempref"
})
@XmlRootElement(name = "rename")
public class Rename {

    protected Pkgref pkgref;
    protected Typeref typeref;
    protected Methodref methodref;
    protected Fieldref fieldref;
    protected Tempref tempref;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String newname;

    /**
     * Gets the value of the pkgref property.
     * 
     * @return
     *     possible object is
     *     {@link Pkgref }
     *     
     */
    public Pkgref getPkgref() {
        return pkgref;
    }

    /**
     * Sets the value of the pkgref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Pkgref }
     *     
     */
    public void setPkgref(Pkgref value) {
        this.pkgref = value;
    }

    /**
     * Gets the value of the typeref property.
     * 
     * @return
     *     possible object is
     *     {@link Typeref }
     *     
     */
    public Typeref getTyperef() {
        return typeref;
    }

    /**
     * Sets the value of the typeref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Typeref }
     *     
     */
    public void setTyperef(Typeref value) {
        this.typeref = value;
    }

    /**
     * Gets the value of the methodref property.
     * 
     * @return
     *     possible object is
     *     {@link Methodref }
     *     
     */
    public Methodref getMethodref() {
        return methodref;
    }

    /**
     * Sets the value of the methodref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Methodref }
     *     
     */
    public void setMethodref(Methodref value) {
        this.methodref = value;
    }

    /**
     * Gets the value of the fieldref property.
     * 
     * @return
     *     possible object is
     *     {@link Fieldref }
     *     
     */
    public Fieldref getFieldref() {
        return fieldref;
    }

    /**
     * Sets the value of the fieldref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Fieldref }
     *     
     */
    public void setFieldref(Fieldref value) {
        this.fieldref = value;
    }

    /**
     * Gets the value of the tempref property.
     * 
     * @return
     *     possible object is
     *     {@link Tempref }
     *     
     */
    public Tempref getTempref() {
        return tempref;
    }

    /**
     * Sets the value of the tempref property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tempref }
     *     
     */
    public void setTempref(Tempref value) {
        this.tempref = value;
    }

    /**
     * Gets the value of the newname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewname() {
        return newname;
    }

    /**
     * Sets the value of the newname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewname(String value) {
        this.newname = value;
    }

}
