module org.jhotdraw.samples.odg extends org.jhotdraw.samples.defaultsample;

import own org.jhotdraw.samples.svg as svg;
import own net.n3.nanoxml export as nanoxml;

replace svg::jhotdraw with jhotdraw;
merge nanoxml, svg::nanoxml export as net.n3.nanoxml nanoxml; 

replace nanoxml with own net.n3.nanoxmlv2_2_1_4patch;
replace svg::batik with own org.apache.batik1_8pre;

export package *;