module org.jhotdraw.samples.svg;

import own org.jhotdraw export as jhotdraw;
import own net.n3.nanoxmlv2_2_1_4patch;
replace jhotdraw::nanoxml with net.n3.nanoxmlv2_2_1_4patch;

//interface
import own org.apache.batik export as batik;

//replace with newer version of batik
import own org.apache.batik1_8pre;

replace batik, jhotdraw::batik with org.apache.batik1_8pre;

export package *;